# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

spring:
  application:
    name: weather-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: 12345
    url: jdbc:postgresql://localhost:5432/weather_db
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
