spring:
  application:
    name: weather-service
  jpa:
    hibernate:
      ddl-auto: update

config:
  open-weather-client:
    url: http://api.openweathermap.org/data/2.5/weather?q={city}&APPID=${OPEN_WEATHER_APP_ID}
